In [1]:
import numpy as np

In [2]:
##create array

##1D array
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a.shape

(5,)

In [5]:
##2D array

b = np.array([[1,2,3],[4,5,6]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b.shape

(2, 3)

In [12]:
a.size

5

In [16]:
c = np.array([3,1,8,4,2])
np.sort(c)

array([1, 2, 3, 4, 8])

In [20]:
x = np.zeros(2)

In [21]:
x

array([0., 0.])

In [28]:
y = np.ones((2,3))
y

array([[1., 1.],
       [1., 1.]])

In [62]:
np.empty([2,2],dtype=int)

array([[613174432,       374],
       [        0,         0]])

In [65]:
z = np.arange(10,20,2)

In [66]:
z

array([10, 12, 14, 16, 18])

In [117]:
c = np.linspace(10,20,num=3)

In [79]:
np.concatenate((np.array([1,2,3]),a),axis=0)

array([1, 2, 3, 1, 2, 3, 4, 5])

In [80]:
a.size

5

In [81]:
x = np.size(a)
x

5

In [86]:
y.shape

(2, 2)

In [90]:
a = np.array([[1,2],[4,5],[7,8]])

In [91]:
a

array([[1, 2],
       [4, 5],
       [7, 8]])

In [92]:
a.shape

(3, 2)

In [94]:
a[0]

array([1, 2])

In [95]:
#minmax,sum,mean,std
#unique items,counts,mul,divison
#reverse 1D and 2D array

In [99]:
a.reshape((2,3))

array([[1, 2, 4],
       [5, 7, 8]])

In [100]:
np.sum(a)

27

In [101]:
np.mean(a)

4.5

In [102]:
np.std(a)

2.5

In [106]:
round(np.var(a),1)

6.2

In [111]:
p = np.array([[1,2],[3,4]])
q = np.array([[5,6]])

In [116]:
np.concatenate((p,q),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
d = c[np.newaxis,:]

In [120]:
d

array([[10., 15., 20.]])

In [121]:
d.shape

(1, 3)

In [122]:
d = c[:,np.newaxis]

In [123]:
d.shape

(3, 1)

In [124]:
d

array([[10.],
       [15.],
       [20.]])

In [125]:
a[:][:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [130]:
a[0][:]

array([1, 2])

In [132]:
a[1][:]

array([4, 5])

In [137]:
a[-1][0]

7

In [139]:
c

array([10., 15., 20.])

In [140]:
c[c>10]

array([15., 20.])

In [141]:
##mathematical operation

a = np.arange(5)
b = np.ones(5)

In [146]:
#sum
np.sum((a,b))

15.0

In [147]:
#broadcasting
a + b

array([1., 2., 3., 4., 5.])

In [148]:
a

array([0, 1, 2, 3, 4])

In [149]:
b

array([1., 1., 1., 1., 1.])

In [150]:
#min
np.min(a)

0

In [151]:
#max
np.max(a)

4

In [152]:
#mean
np.mean(a)

2.0

In [153]:
#std
np.std(a)

1.4142135623730951